:PROPERTIES:
:TOC:      :include all :force (depth) :ignore (this) :local (depth)
:END:
#+TITLE: SysAdmin Cookbook

Here is a collection of neat aliases, scripts, shell-isms, tips, and tricks of the trade that I've found useful in navigating the unix-sphere over the years.

* Table of Content
:PROPERTIES:
:TOC:      :include all :force (depth) :ignore (this) :local (depth)
:END:
:CONTENTS:
- [[#tips--tricks][Tips & Tricks]]
  - [[#general][General]]
    - [[#reuse-arguments-][Reuse arguments (!$)]]
    - [[#last-exit-code-][Last Exit Code ($?)]]
    - [[#-curly-brace-expansion-][{ Curly Brace Expansion }]]
    - [[#ez-backup-with-cp][EZ backup with cp]]
    - [[#repeat-command][Repeat command]]
  - [[#streams][Streams]]
    - [[#stderr][stderr]]
  - [[#sorting-information][Sorting information]]
    - [[#list-all-users][List all users]]
    - [[#list-file-sizes-in-directory][List file sizes in directory]]
  - [[#networking][Networking]]
    - [[#check-if-remote-port-is-open][Check if remote port is open]]
    - [[#check-isp-ip][Check ISP IP]]
  - [[#substrings][Substrings]]
  - [[#misc][Misc]]
- [[#scripts][Scripts]]
  - [[#debugging][Debugging]]
  - [[#ls--la-with-numerical-file-permissionsmode][ls -la with numerical file permissions/mode]]
- [[#reference][Reference]]
:END:
  
* CLI/Shell
** General
*** Reuse arguments (!$)
#+begin_src shell
$ ls /tmp
file1.txt file2.txt file3.txt
$ cd !$
/tmp
#+end_src
*** Last Exit Code ($?)
#+begin_src shell
$ ls /tmp
file1.txt
$ echo $?
0
#+end_src
*** { Curly Brace Expansion }
{ curly brace expansion } can be useful when you run a series of similar commands that differ. Acts as a mini =for= loop.
  #+begin_src shell
  $ touch file-{1,2,3}.md
  $ ls
  # Creates file-1.md file-2.md file-3.md
  #+end_src
*** EZ backup with cp
#+begin_src shell
$ cp file.txt{,.bak}
$ ls -l
file.txt
file.txt.bak
#+end_src
*** Repeat command
Execute a command every two seconds and monitor output.
#+begin_src shell
watch -n2 echo hello
#+end_src

** Streams
Because for some reason I forget them all the time
*** stderr
#+begin_src shell
$ >&2 echo hello
hello
#+end_src

** Sorting information 
*** cut - List all users
#+begin_src shell
$ cut -d: -f1 /etc/passwd
#+end_src

*** du - List file sizes in directory
#+begin_src shell
$ du -sh * | sort -h
#+end_src

** Substrings
Hash =#= will find the first occurence from the start, and modulo =%= will grab the first occurence from the end. =*= for mc-globbin'. If you're feeling greedy, =##= and =%%=.
#+begin_src shell
$ var="death metal"

$ echo ${var#* } # Get second word
metal
$ echo ${var#*d} # Cuts specified substring
eath metal
$ echo ${var##*t} # Cuts everything up until the matched char
al

$ echo ${var% *} # Get first word
death
$ echo ${var%a*} # Cuts specified substring starting from end
death met
$ echo ${var%%a*} # Cuts after occurence
de
#+end_src

** Misc
- =cd -= will switch to the last directory you were in. Fun fact, this trick works with =git= as well.

* Permissions
** Umask
Determines initial permission bits for new files. You are setting the bits that should *NOT* be set on a newly created file (otherwise known as the logical compliment).

Example
    - 027 = (7 - 0 = 7 User), (7 - 2 = 5 Group), (7 - 7 = 0 Other) = 750
    - System wide setting: ~UMASK~ in =/etc/login.defs=
    - Per User setting: users =.bashrc= with ~umask 002~ (or whatever value you'd like)

* Networking
*** Check if remote port is open
#+begin_src shell
$ telnet 1.2.3.4 80
#+end_src

*** Check ISP IP
#+begin_src shell
$ curl ifconfig.co
#+end_src
*** Bonding Methods
Name            Description
balance-rr (0)  transmit packets in sequential order from the first available slave through the last (provides load-balancing and fault tolerance)
active-backup  only one NIC slave in the bond is active, and fallsback to the second slave if the first one fails (provides fault-tolerance)
balance-xor  transmit packet based on a hash of the packets source and destination (provides load-balancing and fault tolerance)
broadcast  transmit network packets on all slave network interfaces (provides fault tolerance)
802.3ad, LACP  aggregation groups that share the same speed and duplex settings. (provides fault tolerance and load-balancing)

* SQL
** Installation
Depending on the system, after installing mariadb/mysql you may need to initialize and start with ~--datadir~ and ~--basedir~:
=mariadb-install-db --user=mysql --basedir=/usr --datadir=/var/lib/mysql=

If you use a non-default location, you can either find it or set it in the [mysqld] section of ~/etc/my.cnf.d/server.cnf~.

Then start with systemd
** Files
~/var/lib/mysql~ needs to have the execute bit set (=chmod u=rwx,g=rwx=), and =mysql:mysql= needs to own the directory.
** Logs
- ~/var/log/mysql~
  If the log isn't here, check the option file (example.cnf). You can grep these variables with:
  =mysqld --help --verbose | grep 'log-error' | tail -1=

- Check option file parameters with:
  =mysqld --print-defaults=

- systemd journal
  =sudo journalctl -u mariadb.service --no-pager=
** General
- =mysql -u root -p=: log in (the password will be blank upon first initil login)

** Create User
#+begin_src sql
CREATE USER 'user'@'localost' IDENTIFIED BY 'some_password';
GRANT ALL PRIVILEGES ON mydb.* TO 'user'@'localhost';
FLUSH PRIVILEGES;
#+end_src

* journalctl
=sudo journalctl -u apache2.service --since today --no-pager=: only show today logging output
* systemd
** Useful commands
=systemctl list-unit-files | grep enabled=: show enabled units
=systemctl --type=service=: show only service units
=systemctl list-units --type=service --all=: Shows all active & inactive service units
=systemctl --failed --type=service=: Shows failed services
=systemctl status -l httpd.service=: Shows detailed status information

** Run level management
=systemctl isolate=: change runlevel
=systemctl get-default=: see default runlevel
+--------------------+--------------------+
|Run Level           |Target              |
+--------------------+--------------------+
|0                   |poweroff.target     |
+--------------------+--------------------+
|1                   |rescue.target       |
+--------------------+--------------------+
|3                   |multi-user.target   |
+--------------------+--------------------+
|5                   |graphical.target    |
+--------------------+--------------------+
|6                   |reboot.target       |
+--------------------+--------------------+
|emergency           |emergency.target    |
+--------------------+--------------------+
** Unit File Reference
*** Service Unit Files
#+begin_src shell
[Unit]
# Describes the unit and dependencies.
Description=Vsftpd ftp daemon
After=network.target
Before=graphical.target

# Describes how to start and stop the service, and request status.
[Service]
Type=forking|oneshot
ExecStart=/usr/sbin/vsftpd /etc/vsftpd/vstpd.conf

# Describes which target this unit needs to be started in.
[Install]
WantedBy=multi-user.target
#+end_src
*** Mount Unit Files
#+begin_src shell
[Unit]
# Describes the unit and dependencies.
Description=Temporary Dir (/tmp/stuff)
Documentation=man:somemanpage
ConditionPathIsSymbolicLink=!/tmp/stuff
DefaultDependencies=no
Conflicts=umount.target
Before=local-fs.target umount.target
After=swap.target

# Describes mount properties
What=tmpfs
Where=/tmp/stuff
Type=tmpfs
Options=mode=1777,strictatime,nosuid,nodev

#+end_src
*** Socket Unit File
#+begin_src shell
[Unit]
Description=Cockpit Web Service Socket
Documentation=man:cockpit-ws(8)
Wants=cockpit-motd.service

[Socket]
# Defines tcp port that systemd should be listening to
ListenStream=9090
# For UDP
ListenDatagram=9090
ExecStartPost=-/usr/share/cockpit/motd/update-motd '' localhost
ExecStartPost=-/bin/ln -snf active.motd /run/cockpit/motd
ExecStopPost=-/bin/ln -snf /usr/share/cockpit/motd/inactive.motd /run/cockpit/motd

[Install]
WantedBy=sockets.target
#+end_src

** Systemd Status
+----------------------------------------+----------------------------------------+
|Status                                  |Description                             |
+----------------------------------------+----------------------------------------+
|Loaded                                  |Unit file has been processed and unit is|
|                                        |active                                  |
+----------------------------------------+----------------------------------------+
|Active(running)                         |Running with one or more active         |
|                                        |processes                               |
+----------------------------------------+----------------------------------------+
|Active(exited)                          |Successfully completed a one-time run   |
+----------------------------------------+----------------------------------------+
|Active(waiting)                         |Running and waiting for an event        |
+----------------------------------------+----------------------------------------+
|Inactive(dead)                          |Not running                             |
+----------------------------------------+----------------------------------------+
|Enabled                                 |Started at boot-time                    |
+----------------------------------------+----------------------------------------+
|Disabled                                |Not started at boot-time                |
+----------------------------------------+----------------------------------------+
|Static                                  |Cannot be enabled but may be started by |
|                                        |another unit automatically              |
+----------------------------------------+----------------------------------------+
* cron/at
- cron
+------------+----------+
|Fields      |          |
+------------+----------+
|minute      |0-59      |
+------------+----------+
|hour        |0-23      |
+------------+----------+
|day-of-month|1-31      |
+------------+----------+
|month       |1-12      |
+------------+----------+
|day-of-week |0-7       |
+------------+----------+

- atd
  Make sure atd.service is enabled and running
  =atq=: check jobs
  Examples: =at noon=, =at 14:00=
* apache/httpd
** Troubleshooting
=systemctl status apache2.service -l --no-pager=: ~-l~ makes sure nothing is truncated
=apachectl configtest=: test the /etc/apache2/apache2.conf configuration

* nginx
=nginx -t=: test nginx configuration
~/logs/error.log~ & ~/logs/access.log~: important log files

** Security Reference
~server_tokens off~: will disable the nginx + version number on error pages.
~add_header X-Frame-Options "SAMEORIGIN";~: indicates if a browser should be allowed to render a page in a <frame> or an <iframe>. Always set this.
~add_header Strict-Transport-Security "max-age=3156000; includeSubdomains; preload";~: used by websites to declare they should only be accessed via HTTPS. The browser must refuse all HTTP connections and prevent users from accepting insecure SSL certs. (NOTE: the browser caches the STS header for the max-age time, so if you mess up your certs while HSTS you're screwed until you flush the site-data in your browser. This is important because if a user isn't technical they will lose access to your site until they clear their own browser which may never happen within the max-age alloted time). ([[https://www.acunetix.com/blog/articles/what-is-hsts-why-use-it/][Reference]])
~add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline'" always;~: Protects the server against certain types of attack including XSS (Cross Site Scripting attacks).

We can limit HTTP methods in the ~location~ directive.
#+begin_src shell
location / {
    limit_except GET HEAD POST { deny all; }
}
#+end_src

** Load Balancer Reference
+------------------------------+------------------------------+
|LB Method                     |Description                   |
+------------------------------+------------------------------+
|round-robin                   |requests are proxied to host  |
|                              |in order they are received    |
+------------------------------+------------------------------+
|least-connected               |requests are proxied to host  |
|                              |with least connections        |
+------------------------------+------------------------------+

#+begin_src shell
http {
    upstream myapp1 {
        server srv1.example.com;
        server srv2.example.com;
        server srv3.example.com;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://myapp1;
        }
    }
}
#+end_src
** Reverse Proxy Reference
#+begin_src shell
server {                    # Make nginx listen on all ipv4 addys on port 443 (0.0.0.0:443)
                            # ssl specifies that all connections accepted should work in SSL mode
                            # http2 configures port to accept http/2 connections (not exlusively)
    listen                  443 ssl http2;
                            # Make nginx listen on all ipv6 addys on port 443 (dangol'ipv6:443)
    listen                  [::]:443 ssl http2;
    # If you want www, just prepend it i.e. www.server.example.sh, add to HTTP redirect
    # if applicable.
    server_name             servername.example.sh;

    # SSL
    ssl_certificate         /etc/letsencrypt/live/server.example.sh/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/server.example.sh/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/server.example.sh/chain.pem;

    # You can include relevant configuration files
    include                 extra/security.conf;

    # reverse proxy
    location  {
        # The internal DNS | IP:Port | localhost:port | container_name:port (if applicable)
        proxy_pass http://internal-server-name.nullvoid.rip:6660;
    }

}

# subdomains redirect
# omit this if applicable
server {
    listen                  443 ssl http2;
    listen                  [::]:443 ssl http2;
    # * will redirect all subdomains i.e. music.server.example.sh;
    server_name             *.servername.example.sh;

    # SSL/Paths to letsencrypt keys
    ssl_certificate         /etc/letsencrypt/live/jellyfin.tr909.sh/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/jellyfin.tr909.sh/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/jellyfin.tr909.sh/chain.pem;

    return                  301 https://servername.example.sh$request_uri;
}

# HTTP redirect
# Will force HTTPS
server {
    listen      80;
    listen      [::]:80;
    server_name .servername.example.sh;

    location / {
        return 301 https://servername.example.sh$request_uri;
    }
}
#+end_src
* Scripts
Smaller functions are in =zsh_functions=, but it's impractical to put larger scripts there so they live in =~/scripts= instead so I can call them with aliases. 

** Debugging
#+begin_src shell
/usr/bin/env bash
set -xv
#+end_src

** ls -la with numerical file permissions/mode
Warning: AWK BLACK MAGIC AHEAD

I dislike calculating rwx with =ls -la=. I'm not sure why this isn't native to ls, but this function will show the permissions bits next to rwx permissions (i.e. 0644)
#+begin_src shell :tangle ~/scripts/ls-with-file-mode-bits.sh :mkdirp yes
ls -l | awk '{
    k = 0
    s = 0
    for( i = 0; i <= 8; i++ )
    {
        k += ( ( substr( $1, i+2, 1 ) ~ /[rwxst]/ ) * 2 ^( 8 - i ) )
    }
    j = 4 
    for( i = 4; i <= 10; i += 3 )
    {
        s += ( ( substr( $1, i, 1 ) ~ /[stST]/ ) * j )
        j/=2
    }
    if ( k )
    {
        printf( "%0o%0o ", s, k )
    }
    print
}'
#+end_src
* Reference
- [[https://github.com/dylanaraps/pure-bash-bible][Pure Bash Bible]]
- [[https://github.com/dylanaraps/pure-sh-bible][Pure POSIX shell Bible]]
